//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Category struct {
	ID            int32 `sql:"primary_key"`
	Name          string
	ParentID      *int32
	Description   *string
	ImageID       *int32
	CreatorUserID *int32
	CreatedAt     time.Time
}
