//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Image = newImageTable("public", "image", "")

type imageTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnInteger
	CreatorUserID postgres.ColumnInteger
	CreatedAt     postgres.ColumnDate

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ImageTable struct {
	imageTable

	EXCLUDED imageTable
}

// AS creates new ImageTable with assigned alias
func (a ImageTable) AS(alias string) *ImageTable {
	return newImageTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ImageTable with assigned schema name
func (a ImageTable) FromSchema(schemaName string) *ImageTable {
	return newImageTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ImageTable with assigned table prefix
func (a ImageTable) WithPrefix(prefix string) *ImageTable {
	return newImageTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ImageTable with assigned table suffix
func (a ImageTable) WithSuffix(suffix string) *ImageTable {
	return newImageTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newImageTable(schemaName, tableName, alias string) *ImageTable {
	return &ImageTable{
		imageTable: newImageTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newImageTableImpl("", "excluded", ""),
	}
}

func newImageTableImpl(schemaName, tableName, alias string) imageTable {
	var (
		IDColumn            = postgres.IntegerColumn("id")
		CreatorUserIDColumn = postgres.IntegerColumn("creator_user_id")
		CreatedAtColumn     = postgres.DateColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, CreatorUserIDColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{CreatorUserIDColumn, CreatedAtColumn}
	)

	return imageTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		CreatorUserID: CreatorUserIDColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
