//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Thread = newThreadTable("public", "thread", "")

type threadTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnInteger
	Name          postgres.ColumnString
	CategoryID    postgres.ColumnInteger
	CreatorUserID postgres.ColumnInteger
	CreatedAt     postgres.ColumnDate

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ThreadTable struct {
	threadTable

	EXCLUDED threadTable
}

// AS creates new ThreadTable with assigned alias
func (a ThreadTable) AS(alias string) *ThreadTable {
	return newThreadTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ThreadTable with assigned schema name
func (a ThreadTable) FromSchema(schemaName string) *ThreadTable {
	return newThreadTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ThreadTable with assigned table prefix
func (a ThreadTable) WithPrefix(prefix string) *ThreadTable {
	return newThreadTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ThreadTable with assigned table suffix
func (a ThreadTable) WithSuffix(suffix string) *ThreadTable {
	return newThreadTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newThreadTable(schemaName, tableName, alias string) *ThreadTable {
	return &ThreadTable{
		threadTable: newThreadTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newThreadTableImpl("", "excluded", ""),
	}
}

func newThreadTableImpl(schemaName, tableName, alias string) threadTable {
	var (
		IDColumn            = postgres.IntegerColumn("id")
		NameColumn          = postgres.StringColumn("name")
		CategoryIDColumn    = postgres.IntegerColumn("category_id")
		CreatorUserIDColumn = postgres.IntegerColumn("creator_user_id")
		CreatedAtColumn     = postgres.DateColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, NameColumn, CategoryIDColumn, CreatorUserIDColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{NameColumn, CategoryIDColumn, CreatorUserIDColumn, CreatedAtColumn}
	)

	return threadTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		Name:          NameColumn,
		CategoryID:    CategoryIDColumn,
		CreatorUserID: CreatorUserIDColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
