//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Users = newUsersTable("public", "users", "")

type usersTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	Email     postgres.ColumnString
	Name      postgres.ColumnString
	Password  postgres.ColumnString
	IsAdmin   postgres.ColumnBool
	BanUntil  postgres.ColumnDate
	CreatedAt postgres.ColumnDate

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UsersTable struct {
	usersTable

	EXCLUDED usersTable
}

// AS creates new UsersTable with assigned alias
func (a UsersTable) AS(alias string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersTable with assigned schema name
func (a UsersTable) FromSchema(schemaName string) *UsersTable {
	return newUsersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UsersTable with assigned table prefix
func (a UsersTable) WithPrefix(prefix string) *UsersTable {
	return newUsersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UsersTable with assigned table suffix
func (a UsersTable) WithSuffix(suffix string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUsersTable(schemaName, tableName, alias string) *UsersTable {
	return &UsersTable{
		usersTable: newUsersTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newUsersTableImpl("", "excluded", ""),
	}
}

func newUsersTableImpl(schemaName, tableName, alias string) usersTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		EmailColumn     = postgres.StringColumn("email")
		NameColumn      = postgres.StringColumn("name")
		PasswordColumn  = postgres.StringColumn("password")
		IsAdminColumn   = postgres.BoolColumn("is_admin")
		BanUntilColumn  = postgres.DateColumn("ban_until")
		CreatedAtColumn = postgres.DateColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, EmailColumn, NameColumn, PasswordColumn, IsAdminColumn, BanUntilColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{EmailColumn, NameColumn, PasswordColumn, IsAdminColumn, BanUntilColumn, CreatedAtColumn}
	)

	return usersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Email:     EmailColumn,
		Name:      NameColumn,
		Password:  PasswordColumn,
		IsAdmin:   IsAdminColumn,
		BanUntil:  BanUntilColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
